openapi: "3.0.0"
info:
  version: 4.0.0
  title: Makini API
  description: Unified API for industrial systems
  license:
    name: Makini Proprietary License
    url: https://www.makini.io/legal#terms
servers:
  - url: https://api.makini.io/v4
paths:
  /organizations:
    get:
      summary: Get list of organizations
      operationId: listOrganizations
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: "#/components/responses/listOrganizations"
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # === Core ===
    cEntity:
      $ref: "models/core/Entity.yaml"
    cLink:
      $ref: "models/core/Link.yaml"
    cRelation:
      $ref: "models/core/Relation.yaml"
    cCollection:
      $ref: "models/core/Collection.yaml"
    # === Taxonomy ===
    iTaxonomy:
      $ref: "models/interfaces/Taxonomy.yaml"
    AssetClassification:
      $ref: "models/taxonomy/AssetClassification.yaml"
    WorkStatus:
      $ref: "models/taxonomy/WorkStatus.yaml"
    WorkClassification:
      $ref: "models/taxonomy/WorkClassification.yaml"
    # === Business ===
    tAddressable:
      $ref: "models/traits/Addressable.yaml"
    Currency:
      $ref: "models/Currency.yaml"
    Address:
      $ref: "models/Address.yaml"
    Contact:
      $ref: "models/Contact.yaml"
    Organization:
      $ref: "models/Organization.yaml"
    Partner:
      $ref: "models/Partner.yaml"
    Vendor:
      $ref: "models/Vendor.yaml"
    Customer:
      $ref: "models/Customer.yaml"
    Account:
      $ref: "models/Account.yaml"
    Employee:
      $ref: "models/Employee.yaml"
    User:
      $ref: "models/User.yaml"
    LaborResource:
      $ref: "models/LaborResource.yaml"
    BusinessUnit:
      $ref: "models/BusinessUnit.yaml"
    SalesPrice:
      $ref: "models/SalesPrice.yaml"
    # === Operational ===
    tDepreciable:
      $ref: "models/traits/Depreciable.yaml"
    tUnderWarranty:
      $ref: "models/traits/UnderWarranty.yaml"
    Site:
      $ref: "models/Site.yaml"
    Asset:
      $ref: "models/Asset.yaml"
    # === Inventory ===
    tStorageLocation:
      $ref: "models/traits/StorageLocation.yaml"
    tPurchaseItem:
      $ref: "models/traits/PurchaseItem.yaml"
    tSalesItem:
      $ref: "models/traits/SalesItem.yaml"
    SupplyOption:
      $ref: "models/SupplyOption.yaml"
    InventoryItem:
      $ref: "models/InventoryItem.yaml"
    StockStorage:
      $ref: "models/StockStorage.yaml"
    StockItem:
      $ref: "models/StockItem.yaml"
    # === Transactional ===
    iTransaction:
      $ref: "models/interfaces/iTransaction.yaml"
    WorkTask:
      $ref: "models/WorkTask.yaml"
    WorkOrder:
      $ref: "models/WorkOrder.yaml"
    # === Misc ===
    Note:
      $ref: "models/Note.yaml"
    UnitOfMeasure:
      $ref: "models/UnitOfMeasure.yaml"
    Location:
      $ref: "models/Location.yaml"
    Meter:
      $ref: "models/Meter.yaml"
    MeterReading:
      $ref: "models/MeterReading.yaml"
  responses:
    listOrganizations:
        $ref: "responses/organizations/listOrganizations.yaml"
