openapi: "3.0.0"
info:
  version: 4.0.0
  title: Makini API
  description: Unified API for industrial systems
servers:
  - url: https://api.makini.io/v4
paths:
  /organizations:
    get:
      summary: Get list of organizations
      operationId: listOrganizations
      responses:
        '200':
          $ref: "#/components/responses/listOrganizations"
components:
  schemas:
    # === Core ===
    cEntity:
      $ref: "./models/core/Entity.yaml"
    cLink:
      $ref: "./models/core/Link.yaml"
    cRelation:
      $ref: "./models/core/Relation.yaml"
    cCollection:
      $ref: "./models/core/Collection.yaml"
    # === Business ===
    tBusinessEntity:
      $ref: "./models/traits/BusinessEntity.yaml"
    Address:
      $ref: "./models/Address.yaml"
    Contact:
      $ref: "./models/Contact.yaml"
    Organization:
      $ref: "./models/Organization.yaml"
  responses:
    listOrganizations:
        $ref: "./responses/organizations/listOrganizations.yaml"
