openapi: "3.0.0"
info:
  version: 4.0.0
  title: Makini API
  description: Unified API for industrial systems
servers:
  - url: https://api.makini.io/v4
paths:
  /organizations:
    get:
      summary: Get list of organizations
      operationId: listOrganizations
      responses:
        '200':
          $ref: "#/components/responses/listOrganizations"
components:
  schemas:
    # === Core ===
    cEntity:
      $ref: "./models/core/Entity.yaml"
    cLink:
      $ref: "./models/core/Link.yaml"
    cRelation:
      $ref: "./models/core/Relation.yaml"
    cCollection:
      $ref: "./models/core/Collection.yaml"
    # === Taxonomy ===
    iTaxonomy:
      $ref: "./models/interfaces/Taxonomy.yaml"
    AssetClassification:
      $ref: "./models/taxonomy/AssetClassification.yaml"
    # === Business ===
    tBusinessEntity:
      $ref: "./models/traits/BusinessEntity.yaml"
    Address:
      $ref: "./models/Address.yaml"
    Contact:
      $ref: "./models/Contact.yaml"
    Organization:
      $ref: "./models/Organization.yaml"
    # === Operational ===
    Site:
      $ref: "./models/Site.yaml"
    Asset:
      $ref: "./models/Asset.yaml"
    # === Inventory ===
    tSupplyItem:
      $ref: "./models/traits/SupplyItem.yaml"
    SupplyOption:
      $ref: "./models/SupplyOption.yaml"
    # === Misc ===
    Note:
      $ref: "./models/Note.yaml"
  responses:
    listOrganizations:
        $ref: "./responses/organizations/listOrganizations.yaml"
