openapi: "3.0.0"
info:
  version: 4.0.0
  title: Makini API
  description: Unified API for industrial systems
  license:
    name: Makini Proprietary License
    url: https://www.makini.io/legal#terms
servers:
  - url: https://api.makini.io/v4
paths:
  /organizations:
    get:
      summary: Get list of organizations
      operationId: listOrganizations
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: "#/components/responses/listOrganizations"
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # === Core ===
    cEntity:
      $ref: "models/core/Entity.yaml"
    cLink:
      $ref: "models/core/Link.yaml"
    cRelation:
      $ref: "models/core/Relation.yaml"
    cCollection:
      $ref: "models/core/Collection.yaml"
    # === Taxonomy ===
    iTaxonomy:
      $ref: "models/interfaces/Taxonomy.yaml"
    AssetClassification:
      $ref: "models/taxonomy/AssetClassification.yaml"
    WorkStatus:
      $ref: "models/taxonomy/WorkStatus.yaml"
    WorkClassification:
      $ref: "models/taxonomy/WorkClassification.yaml"
    PurchaseOrderLineStatus:
      $ref: "models/taxonomy/PurchaseOrderLineStatus.yaml"
    PurchaseOrderStatus:
      $ref: "models/taxonomy/PurchaseOrderStatus.yaml"
    PaymentType:
      $ref: "models/taxonomy/PaymentType.yaml"
    PaymentStatus:
      $ref: "models/taxonomy/PaymentStatus.yaml"
    LocalityType:
      $ref: "models/taxonomy/LocalityType.yaml"
    # === Business ===
    tAddressable:
      $ref: "models/traits/Addressable.yaml"
    tPerson:
      $ref: "models/traits/Person.yaml"
    tConsumable:
      $ref: "models/traits/Consumable.yaml"
    tWorkTarget:
      $ref: "models/traits/WorkTarget.yaml"
    Currency:
      $ref: "models/Currency.yaml"
    Country:
      $ref: "models/Country.yaml"
    Language:
      $ref: "models/Language.yaml"
    Locality:
      $ref: "models/Locality.yaml"
    Address:
      $ref: "models/Address.yaml"
    Contact:
      $ref: "models/Contact.yaml"
    Organization:
      $ref: "models/Organization.yaml"
    Partner:
      $ref: "models/Partner.yaml"
    Vendor:
      $ref: "models/Vendor.yaml"
    Customer:
      $ref: "models/Customer.yaml"
    Account:
      $ref: "models/Account.yaml"
    Employee:
      $ref: "models/Employee.yaml"
    User:
      $ref: "models/User.yaml"
    LaborResource:
      $ref: "models/LaborResource.yaml"
    BusinessUnit:
      $ref: "models/BusinessUnit.yaml"
    SalesPrice:
      $ref: "models/SalesPrice.yaml"
    PaymentMethod:
      $ref: "models/PaymentMethod.yaml"
    # === Operational ===
    tDepreciable:
      $ref: "models/traits/Depreciable.yaml"
    tUnderWarranty:
      $ref: "models/traits/UnderWarranty.yaml"
    Site:
      $ref: "models/Site.yaml"
    Property:
      $ref: "models/Property.yaml"
    Space:
      $ref: "models/Space.yaml"
    Asset:
      $ref: "models/Asset.yaml"
    # === Inventory ===
    tStorageLocation:
      $ref: "models/traits/StorageLocation.yaml"
    tPurchaseItem:
      $ref: "models/traits/PurchaseItem.yaml"
    tSalesItem:
      $ref: "models/traits/SalesItem.yaml"
    SupplyOption:
      $ref: "models/SupplyOption.yaml"
    InventoryItem:
      $ref: "models/InventoryItem.yaml"
    StockStorage:
      $ref: "models/StockStorage.yaml"
    StockItem:
      $ref: "models/StockItem.yaml"
    # === Transactional ===
    iTransaction:
      $ref: "models/interfaces/Transaction.yaml"
    iTransactionLineItem:
      $ref: "models/interfaces/TransactionLineItem.yaml"
    tInbound:
      $ref: "models/traits/Inbound.yaml"
    tOutbound:
      $ref: "models/traits/Outbound.yaml"
    tPaymentBase:
      $ref: "models/traits/PaymentBase.yaml"
    tOrderHeader:
      $ref: "models/traits/OrderHeader.yaml"
    tOrderItem:
      $ref: "models/traits/OrderItem.yaml"
    tWorkUnit:
      $ref: "models/traits/WorkUnit.yaml"
    PurchaseOrder:
      $ref: "models/PurchaseOrder.yaml"
    PurchaseOrderLineItem:
      $ref: "models/PurchaseOrderLineItem.yaml"
    Invoice:
      $ref: "models/Invoice.yaml"
    InvoiceLineItem:
      $ref: "models/InvoiceLineItem.yaml"
    Bill:
      $ref: "models/Bill.yaml"
    BillLineItem:
      $ref: "models/BillLineItem.yaml"
    PaymentInbound:
      $ref: "models/PaymentInbound.yaml"
    PaymentOutbound:
      $ref: "models/PaymentOutbound.yaml"
    WorkTask:
      $ref: "models/WorkTask.yaml"
    WorkOrder:
      $ref: "models/WorkOrder.yaml"
    ProductionOrder:
      $ref: "models/ProductionOrder.yaml"
    MaintenanceTrigger:
      $ref: "models/MaintenanceTrigger.yaml"
    MaintenanceTemplate:
      $ref: "models/MaintenanceTemplate.yaml"
    # === Fiscal ===
    FiscalCalendar:
      $ref: "models/FiscalCalendar.yaml"
    FiscalYear:
      $ref: "models/FiscalYear.yaml"
    FiscalPeriod:
      $ref: "models/FiscalPeriod.yaml"
    Budget:
      $ref: "models/Budget.yaml"
    BudgetLineItem:
      $ref: "models/BudgetLineItem.yaml"
    ScoringScale:
      $ref: "models/ScoringScale.yaml"
    Event:
      $ref: "models/Event.yaml"
    EventParticipation:
      $ref: "models/EventParticipation.yaml"
    # === Misc ===
    Note:
      $ref: "models/Note.yaml"
    UnitOfMeasure:
      $ref: "models/UnitOfMeasure.yaml"
    Location:
      $ref: "models/Location.yaml"
    Meter:
      $ref: "models/Meter.yaml"
    MeterReading:
      $ref: "models/MeterReading.yaml"
    AcademicProgram:
      $ref: "models/AcademicProgram.yaml"
    AcademicPeriod:
      $ref: "models/AcademicPeriod.yaml"
    AcademicAdmission:
      $ref: "models/AcademicAdmission.yaml"
    AcademicCourse:
      $ref: "models/AcademicCourse.yaml"
    AcademicSection:
      $ref: "models/AcademicSection.yaml"
    AcademicAdmissionItem:
      $ref: "models/AcademicAdmissionItem.yaml"
    Student:
      $ref: "models/Student.yaml"
    StudentCohort:
      $ref: "models/StudentCohort.yaml"
    StudentCourseTransfer:
      $ref: "models/StudentCourseTransfer.yaml"
    StudentAidApplication:
      $ref: "models/StudentAidApplication.yaml"
    PersonHold:
      $ref: "models/PersonHold.yaml"
    StudentTranscript:
      $ref: "models/StudentTranscript.yaml"
    StudentCredentials:
      $ref: "models/StudentCredentials.yaml"
  responses:
    listOrganizations:
        $ref: "responses/organizations/listOrganizations.yaml"
