description: >
  Represents a production order for manufacturing or assembly operations, tracking work performed to produce goods.
allOf:
  - $ref: "../index.yaml#/components/schemas/iTransaction"
  - $ref: "../index.yaml#/components/schemas/tOrderHeader"
  - $ref: "../index.yaml#/components/schemas/tWorkUnit"
  - type: object
    properties:
      # Routing reference
      routing:
        nullable: true
        description: Production routing this order follows
        oneOf:
          - $ref: "../index.yaml#/components/schemas/cRelation"
          - $ref: "../index.yaml#/components/schemas/ProductionRouting"
      
      # Production outputs - supports multiple outputs (main, co-products, by-products)
      outputs:
        type: array
        description: Products and items produced by this order
        minItems: 1
        items:
          type: object
          properties:
            outputType:
              type: string
              description: Type of output produced
              enum:
                - main
                - co-product
                - by-product
                - scrap
              default: main
              example: "main"
            item:
              description: The inventory item being produced
              oneOf:
                - $ref: "../index.yaml#/components/schemas/cRelation"
                - $ref: "../index.yaml#/components/schemas/InventoryItem"
            quantityPlanned:
              type: number
              format: double
              description: Planned quantity to be produced
            quantityProduced:
              type: number
              format: double
              description: Actual quantity produced
              default: 0
            quantityYield:
              type: number
              format: double
              description: Yield percentage (produced/planned * 100)
              readOnly: true
            unitOfMeasure:
              description: Unit of measure for the output quantities
              oneOf:
                - $ref: "../index.yaml#/components/schemas/cRelation"
                - $ref: "../index.yaml#/components/schemas/UnitOfMeasure"
            batchNumber:
              type: string
              nullable: true
              description: Batch number for this specific output
            lotNumber:
              type: string
              nullable: true
              description: Lot number for this specific output
            storageLocation:
              nullable: true
              description: Where this output should be stored
              oneOf:
                - $ref: "../index.yaml#/components/schemas/cRelation"
                - $ref: "../index.yaml#/components/schemas/Location"
          required:
            - outputType
            - item
            - quantityPlanned
            - unitOfMeasure
      
      # Production batch tracking (order-level, can be overridden at output level)
      batchNumber:
        type: string
        nullable: true
        description: Default production batch number for all outputs
      
      lotNumber:
        type: string
        nullable: true
        description: Default lot number for all outputs
      
      # Enhanced operation tracking
      currentOperation:
        nullable: true
        description: Currently active operation
        oneOf:
          - $ref: "../index.yaml#/components/schemas/cRelation"
          - $ref: "../index.yaml#/components/schemas/ProductionOrderOperation"
      
      operationCompletionCount:
        type: integer
        readOnly: true
        description: Number of operations completed
        default: 0
      
      operationTotalCount:
        type: integer
        readOnly: true
        description: Total number of operations
      
      percentComplete:
        type: number
        format: float
        readOnly: true
        description: Percentage of operations completed
      
      # Inherited task structure from WorkOrder
      tasks:
        type: array
        items:
          allOf:
            - type: object
              properties:
                order:
                  type: integer
                  description: Execution order within the production order
            - oneOf:
              - $ref: "../index.yaml#/components/schemas/cRelation"    # Reference to external task
              - $ref: "../index.yaml#/components/schemas/WorkItem"     # Simple checklist item
              - $ref: "../index.yaml#/components/schemas/WorkTask"     # Complex task with full tWorkUnit capabilities
      
      # Links structure similar to WorkOrder
      _links:
        type: object
        properties:
          operations:
            $ref: "../../index.yaml#/components/schemas/cLink"
            description: Link to production order operations
          materials:
            $ref: "../../index.yaml#/components/schemas/cLink" # OrderMaterial
          resources:
            $ref: "../../index.yaml#/components/schemas/cLink" # OrderResource
          outputs:
            $ref: "../../index.yaml#/components/schemas/cLink"
            description: Link to all output items produced
          routing:
            $ref: "../../index.yaml#/components/schemas/cLink"
            description: Master routing reference
        additionalProperties:
          $ref: "../../index.yaml#/components/schemas/cLink"
