description: >
  Represents a production order for manufacturing or assembly operations, tracking work performed to produce goods.
allOf:
  - $ref: "../index.yaml#/components/schemas/iTransaction"
  - $ref: "../index.yaml#/components/schemas/tOrderHeader"
  - $ref: "../index.yaml#/components/schemas/tWorkUnit"
  - type: object
    properties:
      # Routing reference
      routing:
        nullable: true
        description: Production routing this order follows
        oneOf:
          - $ref: "../index.yaml#/components/schemas/cRelation"
          - $ref: "../index.yaml#/components/schemas/ProductionRouting"
      
      # Production-specific output with quantities
      output:
        type: object
        description: The product or item being produced by this order with quantity tracking
        properties:
          item:
            description: The inventory item being produced
            oneOf:
              - $ref: "../index.yaml#/components/schemas/cRelation"
              - $ref: "../index.yaml#/components/schemas/InventoryItem"
          quantityPlanned:
            type: number
            format: double
            description: Planned quantity to be produced
          quantityProduced:
            type: number
            format: double
            description: Actual quantity produced
            default: 0
          quantityYield:
            type: number
            format: double
            description: Yield percentage (produced/planned * 100)
            readOnly: true
          unitOfMeasure:
            description: Unit of measure for the output quantities
            oneOf:
              - $ref: "../index.yaml#/components/schemas/cRelation"
              - $ref: "../index.yaml#/components/schemas/UnitOfMeasure"
        required:
          - item
          - quantityPlanned
          - unitOfMeasure
      
      # Production batch and lot tracking
      batchNumber:
        type: string
        nullable: true
        description: Production batch number for tracking and quality control
      
      lotNumber:
        type: string
        nullable: true
        description: Lot number for inventory tracking and traceability
      
      # Enhanced operation tracking
      currentOperation:
        nullable: true
        description: Currently active operation
        oneOf:
          - $ref: "../index.yaml#/components/schemas/cRelation"
          - $ref: "../index.yaml#/components/schemas/ProductionOrderOperation"
      
      operationCompletionCount:
        type: integer
        readOnly: true
        description: Number of operations completed
        default: 0
      
      operationTotalCount:
        type: integer
        readOnly: true
        description: Total number of operations
      
      percentComplete:
        type: number
        format: float
        readOnly: true
        description: Percentage of operations completed
      
      # Inherited task structure from WorkOrder
      tasks:
        type: array
        items:
          allOf:
            - type: object
              properties:
                order:
                  type: integer
                  description: Execution order within the production order
            - oneOf:
              - $ref: "../index.yaml#/components/schemas/cRelation"    # Reference to external task
              - $ref: "../index.yaml#/components/schemas/WorkItem"     # Simple checklist item
              - $ref: "../index.yaml#/components/schemas/WorkTask"     # Complex task with full tWorkUnit capabilities
      
      # Links structure similar to WorkOrder
      _links:
        type: object
        properties:
          operations:
            $ref: "../../index.yaml#/components/schemas/cLink"
            description: Link to production order operations
          materials:
            $ref: "../../index.yaml#/components/schemas/cLink" # OrderMaterial
          resources:
            $ref: "../../index.yaml#/components/schemas/cLink" # OrderResource
          output:
            $ref: "../../index.yaml#/components/schemas/cLink"    # Link to output inventory item
          routing:
            $ref: "../../index.yaml#/components/schemas/cLink"
            description: Master routing reference
        additionalProperties:
          $ref: "../../index.yaml#/components/schemas/cLink"
